<?php

// autoload-files.php @generated by Strauss
// @see https://github.com/BrianHenryIE/strauss/

require_once __DIR__ . '/symfony/var-dumper/Resources/functions/dump.php';
require_once __DIR__ . '/symfony/polyfill-mbstring/bootstrap.php';
